= Build Status Checker

A utility container image that could be used as init containers with Kuberenetes deployments which can use the Knative build to build the image, that will be used in the deployment

== Pre-requisite

* The Kubernetes environment should have https://github.com/knative/build[Knative Build] deployed in your kubernetes environment

== How to use ?

Add the following init-container definition to the kubernetes deployment

[source,yaml]
----
    initContainers:
    - name: build-status-checker
        image: quay.io/rhdevelopers/build-status-checker
        args:
         - poll
         - --buildname=my-build
----

== Commands

The application right now supports only one command called `poll`  the polls a named build. The `poll` command has only one parameter called `buildname` i.e the name of the build that needs to be polled and checked for status

=== Global Parameters

The application supports the following parameters:

- loglevel: The level of logging you want from the application, all log levels from https://github.com/sirupsen/logrus are applicable
- kubeconfig: The location of kubeconfig file if you are running out of the cluster


